---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: Colorize root shell prompt
    lineinfile:
      path: /root/.bashrc
      line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
      state: present

  - name: Alias vi to vim
    lineinfile:
      path: /root/.bashrc
      line: "alias vi='vim'"
      state: present

  - name: Create vim configuration file
    file:
      path: /root/.vimrc
      state: touch
      owner: root
      group: root
      mode: 0644

  - name: Configure vim
    blockinfile:
      path: /root/.vimrc
      block: |
        set nocompatible
        set number
        set autoindent
        syntax on
        highlight Comment ctermfg=LightCyan
      marker: ""
      state: present

  - name: Disable GSSAPIAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
      state: present

  - name: Install packages
    apt: 
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - wget
      - net-tools
    when: ansible_os_family == "Debian"

  - name: Install open-vm-tools
    apt:
      name: open-vm-tools
      state: latest
    when:
      - ansible_os_family == "Debian"
      - ansible_virtualization_type == "VMware"